# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’
# Uncomment this line if you're using Swift
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'SafeRide' do
	pod "SwiftDDP", "~> 0.3.0"
	pod 'GoogleMaps'
	pod 'Locksmith'
end

target 'SafeRideTests' do

end

target 'SafeRideUITests' do

end

target 'CoreDataService' do

end

target 'CoreDataServiceTests' do

end

